pipeline {
    agent any
    stages {
        stage('Env') {
            steps {
                sh "env | sort"
            }
        }
        stage('GitBuild') {
            steps {
                git 'https://github.com/ruiyang/react_demo'
            }
        }

    }
}
